import Wesanb from '../iamge/sheet1/wesanb.png';
import Radwan from '../iamge/sheet1/radwan.png';
import Madaa from '../iamge/sheet1/madaa.png';
import Msireg from '../iamge/sheet1/msireg.png';
import Oad from '../iamge/sheet1/oad.png';
import Rada from '../iamge/sheet1/rada.png';
import Reeima from '../iamge/sheet1/reeima.png';
import Hswa from '../iamge/sheet1/hswa.png';
import Bhwan from '../iamge/sheet1/bhwan.png';
import Reem from '../iamge/sheet1/reem.png';
import Sharf from '../iamge/sheet1/sharf.png';
import Roam from '../iamge/sheet1/roam.png';
import Soda from '../iamge/sheet1/soda.png';
import Tib from '../iamge/sheet1/tib.png';
import Btna from '../iamge/sheet1/btna.png';
import Thoaba from '../iamge/sheet1/thoaba.png'
import Khdar from '../iamge/sheet1/khdar.png'
import marba from '../iamge/sheet1/marba.png'
import ashran from '../iamge/sheet1/ashran.png'
import tndha from '../iamge/sheet1/tndha.png'
import almaawen from '../iamge/sheet1/almaawen.png'
import atheb from '../iamge/sheet1/atheb.png'
import alaina from '../iamge/sheet1/alaina.png'
import abha from '../iamge/sheet1/abha.png'
import atodkhamis from '../iamge/sheet1/atodkhamis.png'
import hgla from '../iamge/sheet1/hgla.png'
import thmania from '../iamge/sheet1/thmania.png'
import althfn from '../iamge/sheet1/althfn.png'
import sbh from '../iamge/sheet1/sbh.png'
import agda from '../iamge/sheet1/38da.png'
import wstmrma from '../iamge/sheet1/wstmrma.png'
import atodg from '../iamge/sheet1/atodg.png'
import aodgof from '../iamge/sheet1/aodgof.png'
import al3sm from '../iamge/sheet1/al3sm.png'
import thll from '../iamge/sheet1/thll.png'

// import  from '../iamge/sheet2/.png'
import alamal from '../iamge/sheet2/alamal.png'
import almshreb from '../iamge/sheet2/almshreb.png'
import alramid from '../iamge/sheet2/alramid.png'
import arara from '../iamge/sheet2/arara.png'
import bsam from '../iamge/sheet2/bsam.png'
import griha from '../iamge/sheet2/griha.png'
import khader from '../iamge/sheet2/khader.png'
import wgier from '../iamge/sheet2/wgier.png'
import zhra from '../iamge/sheet2/zhra.png'
import derham from '../iamge/sheet2/derham.png'
import gbda from '../iamge/sheet2/gbda.png'
import hrga from '../iamge/sheet2/hrga.png'
import fgais from '../iamge/sheet2/fgais.png'
import nhra from '../iamge/sheet2/nhra.png'
import hdila from '../iamge/sheet2/hdila.png'
import mrga from '../iamge/sheet2/mrga.png'
import smakia from '../iamge/sheet2/smakia.png'
import gaeel from '../iamge/sheet2/gaeel.png'
import fitlha from '../iamge/sheet2/fitlha.png'
import shergeb from '../iamge/sheet2/shergeb.png'
import shrom from '../iamge/sheet2/shrom.png'
import normal from '../iamge/sheet2/normal.png'
import hjrzher from '../iamge/sheet2/hjrzher.png'
import gofmamer from '../iamge/sheet2/gofmamer.png'
import rshed from '../iamge/sheet2/rshed.png'
import ananm from '../iamge/sheet2/ananm.png'
import hgla1 from '../iamge/sheet2/hgla.png'
import araer from '../iamge/sheet2/araer.png'
import feed from '../iamge/sheet2/feed.png'
import ktam from '../iamge/sheet2/ktam.png'
import froon from '../iamge/sheet2/froon.png'
import shabhrja from '../iamge/sheet2/shabhrja.png'
import frdan from '../iamge/sheet2/frdan.png'
import saroi from '../iamge/sheet2/saroi.png'
import osran from '../iamge/sheet2/osran.png'
import algoha from '../iamge/sheet2/algoha.png'
import alaiza from '../iamge/sheet2/alaiza.png'
import mohzam from '../iamge/sheet2/mohzam.png'
import wadidaf from '../iamge/sheet2/wadidaf.png'
import farha from '../iamge/sheet2/farha.png'
import abugadaa from '../iamge/sheet2/abugadaa.png'
import dafaa from '../iamge/sheet2/dafaa.png'
import thabt from '../iamge/sheet2/thabt.png'
import gilan from '../iamge/sheet2/gilan.png'
import eifaa from '../iamge/sheet2/eifaa.png'



// import  from '../iamge/sheet3/.png'
import gdar from '../iamge/sheet3/gdar.png'
import kas from '../iamge/sheet3/kas.png'
import kashm from '../iamge/sheet3/kashm.png'
import klsa from '../iamge/sheet3/klsa.png'
import mara from '../iamge/sheet3/mara.png'
import sarom from '../iamge/sheet3/sarom.png'
import sdwan from '../iamge/sheet3/sdwan.png'
import shri from '../iamge/sheet3/shri.png'
import sarba from '../iamge/sheet3/sarba.png'
import gra from '../iamge/sheet3/gra.png'
import hlba from '../iamge/sheet3/hlba.png'
import trif from '../iamge/sheet3/trif.png'
import zhna from '../iamge/sheet3/zhna.png'
import shdad from '../iamge/sheet3/shdad.png'
import mgarda from '../iamge/sheet3/mgarda.png'
import mska from '../iamge/sheet3/mska.png'
import gobaa from '../iamge/sheet3/gobaa.png'
import graba from '../iamge/sheet3/graba.png'
import kars from '../iamge/sheet3/kars.png'
import aiash from '../iamge/sheet3/aiash.png'
import badora from '../iamge/sheet3/badora.png'
import galb from '../iamge/sheet3/galb.png'
import oas from '../iamge/sheet3/oas.png'
import thama from '../iamge/sheet3/thama.png'
import bagif from '../iamge/sheet3/bagif.png'
import naba from '../iamge/sheet3/naba.png'
import zhban from '../iamge/sheet3/zhban.png'
import hrgab from '../iamge/sheet3/hrgab.png'
import kder from '../iamge/sheet3/kder.png'
import foha from '../iamge/sheet3/foha.png'
import shibana from '../iamge/sheet3/shibana.png'
import king from '../iamge/sheet3/king.png'
import bnugis from '../iamge/sheet3/bnugis.png'
import trjs from '../iamge/sheet3/trjs.png'
import shot from '../iamge/sheet3/shot.png'
import ubh from '../iamge/sheet3/ubh.png'
import tbalh from '../iamge/sheet3/tbalh.png'









const Sade = [
   
    {
      "north": "18.280217",
      "east": "42.33365",
      "date": "1406",
      "Sirens": 1,
      "Portals": 1,
      "valves": 0,
      "Lighting": 0,
      "Generator": 1,
      "Guard": 1,
      "management": 1,
      "i_security": 1,
      "capacity": 35000,
      "high": 9,
      "length": 12,
      "type": "خرساني",
      "purpose": "حماية",
      "d_name": "العوص",
      "governorate": "رجال المع",
      "id": "1",
      "photo":Oad,
      "spillyway_h": 55,
    },

    {
      "north":"18.235867",
      "east":"42.178497",
      "date": "1403هـ",
      "Sirens": 1,
      "Portals": 0,
      "valves": 0,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 50000,
      "high": 8,
      "length": 11,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "ريم",
      "governorate": "رجال المع",
      "id": "2",
      "photo":Reem,
      "spillyway_h": 55,
    },

    {
      "north": "18.29138",
      "east": "42.444115",
      "date": "1404هـ",
      "Sirens": 1,
      "Portals": 0,
      "valves": 0,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 60000,
      "high": 12,
      "length": 15,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "ال عاصم",
      "governorate": "أبها",
      "id": "3",
      "photo": al3sm,
      "spillyway_h": 70,
    },
    {
      "north": "18.236389",
      "east": "42.412778",
      "date": "1404هـ",
      "Sirens": 1,
      "Portals": 0,
      "valves": 0,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 340000,
      "high": 10,
      "length": 13,
      "type": "خرساني",
      "purpose": "حماية",
      "d_name": "السوده(المقضى)",
      "governorate": "أبها",
      "id": "4",
      "photo": Soda,
      "spillyway_h": 28,
    },
    {
      "north": "18.266239",
      "east": "42.270122",
      "date": "1404",
      "Sirens": 1,
      "Portals": 0,
      "valves": 1,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 230000,
      "high": 8,
      "length": 11,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "ثعابه",
      "governorate": "رجال المع",
      "id": "6",
      "photo":Thoaba,
      "spillyway_h": 100,
    },
    {
      "north": "18.858056",
      "east": "42.655278",
      "date": "1404",
      "Sirens": 1,
      "Portals": 0,
      "valves": 0,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 151800,
      "high": 10,
      "length": 13,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "البطنه",
      "governorate": "خميس مشيط",
      "id": "7",
      "photo":Btna,
      "spillyway_h": 360,
    },
    {
      "north": "18.329722",
      "east": "42.0925",
      "date": "1406",
      "Sirens": 1,
      "Portals": 1,
      "valves": 1,
      "Lighting": 1,
      "Generator": 1,
      "Guard": 1,
      "management": 1,
      "i_security": 1,
      "capacity": 1500000,
      "high": 13,
      "length": 16,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "روام",
      "governorate": "رجال المع",
      "id": "8",
      "photo":Roam,
      "spillyway_h": 57,
    },
    {
      "north": "18.355",
      "east": "42.386389",
      "date": "1431هـ",
      "Sirens": 1,
      "Portals": 1,
      "valves": 1,
      "Lighting": 1,
      "Generator": 1,
      "Guard": 1,
      "management": 1,
      "i_security": 1,
      "capacity": 230000,
      "high": 12,
      "length": 15,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "ريمه",
      "governorate": "أبها",
      "id": "9",
      "photo":Reeima,
      "spillyway_h": 205,
    },
    {
      "north": "18.447222",
      "east": "43.371389",
      "date": "1432هـ",
      "Sirens": 1,
      "Portals": 1,
      "valves": 1,
      "Lighting": 1,
      "Generator": 0,
      "Guard": 0,
      "management": 1,
      "i_security": 1,
      "capacity": 355650,
      "high": 6,
      "length": 8,
      "type": "ترابي",
      "purpose": "استعاضة",
      "d_name": "طليحة الشرف",
      "governorate": "ابها",
      "id": "10",
      "photo":Sharf,
      "spillyway_h": 281,
    },
      {
        "north": "18.358056",
        "east": "42.240833",
        "date": "1406",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 182000,
        "high": 20,
        "length": 23,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "وسانب",
        "governorate": "رجال المع",
        "id": "12",
        "photo": Wesanb,
        "spillyway_h": 100,
      },
      {
        "north": "18.236714",
        "east": "42.205464",
        "date": "1406",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 192000,
        "high": 15,
        "length": 18,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "راده",
        "governorate": "رجال المع",
        "id": "13",
        "photo": Rada,
        "spillyway_h": 70,
      },
      {
        "north": "18.053333",
        "east": "42.2683",
        "date": "1403هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 300000,
        "high": 5.5,
        "length": 8,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "العاينه",
        "governorate": "رجال المع",
        "id": "14",
        "photo": alaina,
        "spillyway_h": 80,
      },
      {
        "north": "18.578056",
        "east": "42.818056",
        "date": "1437",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 357160,
        "high": 4,
        "length": 6.5,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "روضان",
        "governorate": "خميس مشيط",
        "id": "15",
        "photo": Radwan,
        "spillyway_h": 169,
      },
      {
        "north": "18.263611",
        "east": "43.601389",
        "date": "1417هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 500000,
        "high": 15,
        "length": 18,
        "type": "خرساني",
        "purpose": "جوفي",
        "d_name": "وسط مرمى",
        "governorate": "خميس مشيط",
        "id": "16",
        "photo": wstmrma,
        "spillyway_h": 85,
      },
      {
        "north": "18.295806",
        "east": "42.654453",
        "date": "1398هـ",
        "Sirens": 0,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 1000000,
        "high": 8,
        "length": 12,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "حجلا",
        "governorate": "أبها",
        "id": "17",
        "photo": hgla,
        "spillyway_h": 180,
      },
      {
        "north": "18.6825",
        "east": "42.413611",
        "date": "1432هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 121560,
        "high": 8,
        "length": 11,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "بهوان",
        "governorate": "أبها",
        "id": "18",
        "photo": Bhwan,
        "spillyway_h": 275,
      },
      {
        "north": "18.367438",
        "east": "42.361866",
        "date": "1403هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 90000,
        "high": 10,
        "length": 13,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "طبب",
        "governorate": "أبها",
        "id": "19",
        "photo": Tib,
        "spillyway_h": 50,
      },
      {
        "north": "19.049444",
        "east": "42.908611",
        "date": "1430هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 433000,
        "high": 6,
        "length": 9,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "المسيرق",
        "governorate": "خميس مشيط",
        "id": "20",
        "photo": Msireg,
        "spillyway_h": 84,
      },
      {
        "north": "18.787722",
        "east": "43.210619",
        "date": "1404هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 4250000,
        "high": 6.5,
        "length": 8,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "المضه",
        "governorate": "خميس مشيط",
        "id": "21",
        "photo": Madaa,
        "spillyway_h": 1070,
      },
   
      {
        "north": "18.204321",
        "east": "42.31512",
        "date": "1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 200000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "حسوه",
        "governorate": "رجال المع",
        "id": "23",
        "photo": Hswa,
        "spillyway_h": 45,
      },
      {
        "north": "18.677844",
        "east": "42.331407",
        "date": "1432هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 229700,
        "high": 10,
        "length": 13,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "صبح",
        "governorate": "أبها",
        "id": "24",
        "photo": sbh,
        "spillyway_h": 130,
      },
      {
        "north": "18.023",
        "east": "42.7637",
        "date": "1405",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 300000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "تمنية",
        "governorate": "أبها",
        "id": "25",
        "photo": thmania,
        "spillyway_h": 100,
      },
      {
        "north": "18.650156",
        "east": "42.397278",
        "date": "1404هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 400000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "الماوين",
        "governorate": "أبها",
        "id": "26",
        "photo": almaawen,
        "spillyway_h": 120,
      },
      {
        "north": "18.269167",
        "east": "42.438056",
        "date": "1404",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 1500000,
        "high": 31.5,
        "length": 38,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "عشران",
        "governorate": "أبها",
        "id": "27",
        "photo": ashran,
        "spillyway_h": 111,
      },
      {
        "north": "18.850858",
        "east": "42.855842",
        "date": "1405هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 0,
        "Generator": 1,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 1064000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "اثب",
        "governorate": "خميس مشيط",
        "id": "28",
        "photo": atheb,
        "spillyway_h": 95,
      },
      {
        "north": "18.695833",
        "east": "42.527222",
        "date": "1431هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 1128733,
        "high": 6,
        "length": 9,
        "type": "ترابي",
        "purpose": "حماية",
        "d_name": "خضار الحيمة",
        "governorate": "خميس مشيط",
        "id": "29",
        "photo": Khdar,
        "spillyway_h": 648,
      },
      {
        "north": "18.403611",
        "east": "42.4",
        "date": "1405",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 0,
        "Generator": 1,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 140000,
        "high": 10.5,
        "length": 13.5,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "تهلل",
        "governorate": "أبها",
        "id": "30",
        "photo": thll,
        "spillyway_h": 140,
      },
      {
        "north": "18.209935",
        "east": "42.488654",
        "date": "1394هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 0,
        "i_security": 1,
        "capacity": 2130000,
        "high": 22.5,
        "length": 25.5,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "أبها",
        "governorate": "أبها",
        "id": "31",
        "photo": abha,
        "spillyway_h": 350,
      },
      {
        "north": "18.312683",
        "east": "42.876847",
        "date": "1404هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 0,
        "capacity": 4200000,
        "high": 10,
        "length": 16,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "تندحه",
        "governorate": "خميس مشيط",
        "id": "32",
        "photo": tndha,
        "spillyway_h": 120,
      },
      {
        "north": "18.260411",
        "east": "42.715894",
        "date": "1402هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 0,
        "i_security": 1,
        "capacity": 6240000,
        "high": 16,
        "length": 22,
        "type": "ركامي",
        "purpose": "للشرب",
        "d_name": "عتود",
        "governorate": "خميس مشيط",
        "id": "33",
        "photo": atodkhamis,
        "spillyway_h": 340,
      },
      {
        "north": "17.850739",
        "east": "42.386114",
        "date": "1428هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 0,
        "Generator": 1,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 7000000,
        "high": 0,
        "length": 28,
        "type": "جوفي",
        "purpose": "للشرب",
        "d_name": "عتود الجوفي",
        "governorate": "أبها",
        "id": "34",
        "photo": aodgof,
        "spillyway_h": 456,
      },
      {
        "north": "17.903333",
        "east": "42.384722",
        "date": "1429",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 10000000,
        "high": 26,
        "length": 32,
        "type": "ترابي",
        "purpose": "للشرب",
        "d_name": "مربة",
        "governorate": "مربة",
        "id": "35",
        "photo": marba,
        "spillyway_h": 215,
      },
      {
        "north": "17.900556",
        "east": "42.471111",
        "date": "1429",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 10000000,
        "high": 29,
        "length": 35,
        "type": "ترابي",
        "purpose": "للشرب",
        "d_name": "عتود",
        "governorate": "أبها",
        "id": "36",
        "photo": atodg,
        "spillyway_h": 227,
      },
      {
        "north": "18.280428",
        "east": "42.864847",
        "date": "1406هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 3000000,
        "high": 7,
        "length": 10,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "عقده",
        "governorate": "خميس مشيط",
        "id": "37",
        "photo": agda,
        "spillyway_h": 220,
      },
      {
        "north": "19.245278",
        "east": "43.138611",
        "date": "1440هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 639068,
        "high": 5.5,
        "length": 8.5,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "الثفن",
        "governorate": "خميس مشيط",
        "id": "38",
        "photo": althfn,
        "spillyway_h": 189,
      },
      {
        "north": "18.110833",
        "east": "43.142778",
        "date": "1431",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 26105,
        "high": 4.5,
        "length": 7.5,
        "type": "ترابي",
        "purpose": "حماية",
        "d_name": "القريحاء",
        "governorate": "سراة عبيده",
        "id": "39",
        "photo": griha,
        "spillyway_h": 186.5,
      },
      {
        "north": "17.981392",
        "east": "43.20996",
        "date": "1424",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 90000,
        "high": 5.5,
        "length": 8,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "الرميد",
        "governorate": "سراة عبيده",
        "id": "40",
        "photo": alramid ,
        "spillyway_h": 105,
      },
      {
        "north": "17.941944",
        "east": "43.225833",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 100000,
        "high": 7,
        "length": 10,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "زهره بني بشر",
        "governorate": "سراة عبيده",
        "id": "41",
        "photo": zhra,
        "spillyway_h": 175,
      },
      {
        "north": "18.153911",
        "east": "43.1882",
        "date": "1424",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 108000,
        "high": 9,
        "length": 12,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "خضار",
        "governorate": "سراة عبيده",
        "id": "42",
        "photo": khader,
        "spillyway_h": 241,
      },
      {
        "north": "18.076667",
        "east": "43.235556",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 110000,
        "high": 13,
        "length": 16,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "العمل )زهير(",
        "governorate": "سراة عبيده",
        "id": "43",
        "photo": alamal,
        "spillyway_h": 81,
      },
      {
        "north": "18.035556",
        "east": "43.188611",
        "date": "1432",
        "Sirens": 0,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 47700,
        "high": 3,
        "length": 6,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "ال بسام",
        "governorate": "سراة عبيده",
        "id": "44",
        "photo": bsam,
        "spillyway_h": 176,
      },
      {
        "north": "18.1383",
        "east": "43.134147",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 111170,
        "high": 6,
        "length": 9,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "المشرب",
        "governorate": "سراة عبيده",
        "id": "45",
        "photo": almshreb,
        "spillyway_h": 391,
      },
      {
        "north": "18.014143",
        "east": "43.328845",
        "date": "هـ1425",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 100000,
        "high": 4.25,
        "length": 6,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "الوقيره",
        "governorate": "ظهران الجنوب",
        "id": "46",
        "photo": wgier,
        "spillyway_h": 105,
      },
      {
        "north": "17.932042",
        "east": "43.286525",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 79229,
        "high": 9,
        "length": 12,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "محالة عرعرة",
        "governorate": "ظهران الجنوب",
        "id": "47",
        "photo": arara,
        "spillyway_h": 113,
      },
      {
        "north": "17.993643",
        "east": "43.264752",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 86700,
        "high": 12,
        "length": 15,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "ال درهم",
        "governorate": "ظهران الجنوب",
        "id": "48",
        "photo": derham,
        "spillyway_h": 168,
      },
      {
        "north": "18.055833",
        "east": "42.951492",
        "date": "هـ1425",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 1,
        "capacity": 150000,
        "high": 11.5,
        "length": 14,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "الغيالن",
        "governorate": "احد رفيده",
        "id": "49",
        "photo": gilan,
        "spillyway_h": 150,
      },
      {
        "north": "18.050833",
        "east": "42.814444",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 1,
        "capacity": 160000,
        "high": 6.5,
        "length": 9.5,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "ال حديله",
        "governorate": "احد رفيده",
        "id": "50",
        "photo": hdila,
        "spillyway_h": 265,
      },
      {
        "north": "18.0225",
        "east": "43.28201",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 102700,
        "high": 10,
        "length": 13,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "الفقاعيس",
        "governorate": "سراة عبيده",
        "id": "51",
        "photo": fgais,
        "spillyway_h": 105,
      },
      {
        "north": "17.790833",
        "east": "43.417222",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 0,
        "capacity": 74700,
        "high": 11,
        "length": 14,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "ال عيفه",
        "governorate": "ظهران الجنوب",
        "id": "52",
        "photo": eifaa,
        "spillyway_h": 115,
      },
      {
        "north": "17.634683",
        "east": "43.525867",
        "date": "هـ1405",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 260000,
        "high": 10,
        "length": 13,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "القبضه",
        "governorate": "ظهران الجنوب",
        "id": "53",
        "photo": gbda,
        "spillyway_h": 50,
      },
      {
        "north": "17.915733",
        "east": "43.332072",
        "date": "1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 280000,
        "high": 8,
        "length": 11.5,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "الحرجه",
        "governorate": "الحرجة",
        "id": "54",
        "photo": hrga,
        "spillyway_h": 160,
      },
      {
        "north": "18.073139",
        "east": "42.829531",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 1,
        "capacity": 90375,
        "high": 6,
        "length": 9,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "الصمخية",
        "governorate": "احد رفيده",
        "id": "55",
        "photo": smakia,
        "spillyway_h": 264,
      },
      {
        "north": "18.162483",
        "east": "42.797581",
        "date": "هـ1403",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 300000,
        "high": 8,
        "length": 11,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "المراغه",
        "governorate": "احد رفيده",
        "id": "56",
        "photo": mrga,
        "spillyway_h": 233,
      },
      {
        "north": "18.283333",
        "east": "43.29365",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 350000,
        "high": 7,
        "length": 10,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "هجرة زهير",
        "governorate": "سراة عبيده",
        "id": "57",
        "photo": hjrzher,
        "spillyway_h": 100,
      },
      {
        "north": "17.993107",
        "east": "43.202364",
        "date": "هـ1423",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 350000,
        "high": 10,
        "length": 13,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "النحره",
        "governorate": "سراة عبيده",
        "id": "58",
        "photo": nhra,
        "spillyway_h": 95,
      },
      {
        "north": "18.212241",
        "east": "43.168404",
        "date": "هـ1429",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 400000,
        "high": 10,
        "length": 13,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "جوف المعمر",
        "governorate": "سراة عبيده",
        "id": "60",
        "photo": gofmamer,
        "spillyway_h": 270,
      },
      {
        "north": "17.958567",
        "east": "43.264369",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 480000,
        "high": 8,
        "length": 11,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "العاديه",
        "governorate": "ظهران الجنوب",
        "id": "61",
        "photo": normal,
        "spillyway_h": 170,
      },
      {
        "north": "18.25985",
        "east": "43.2309",
        "date": "1419",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 500000,
        "high": 8.5,
        "length": 11,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "الرشيد",
        "governorate": "سراة عبيده",
        "id": "62",
        "photo": rshed,
        "spillyway_h": 149,
      },
      {
        "north": "17.758889",
        "east": "43.470278",
        "date": "هـ1430",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 500000,
        "high": 7,
        "length": 10,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "الثابت",
        "governorate": "ظهران الجنوب",
        "id": "63",
        "photo": thabt,
        "spillyway_h": 120,
      },
      {
        "north": "18.132222",
        "east": "43.0025",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 342926,
        "high": 9,
        "length": 12,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "الهجلة",
        "governorate": "احد رفيده",
        "id": "64",
        "photo": hgla1,
        "spillyway_h": 129,
      },
      {
        "north": "17.783333",
        "east": "43.508056",
        "date": "هـ1428",
        "Sirens": 1,
        "Portals": 1,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 0,
        "i_security": 1,
        "capacity": 748000,
        "high": 7,
        "length": 9,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "افياض الطلحه",
        "governorate": "ظهران الجنوب",
        "id": "65",
        "photo": fitlha,
        "spillyway_h": 400,
      },
      {
        "north": "17.881967",
        "east": "43.350467",
        "date": "1403",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 790000,
        "high": 9,
        "length": 12,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "شراقب",
        "governorate": "ظهران الجنوب",
        "id": "66",
        "photo": shergeb,
        "spillyway_h": 70,
      },
      {
        "north": "17.903486",
        "east": "43.470911",
        "date": "هـ1399",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 1000000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "سروم الحرجه",
        "governorate": "ظهران الجنوب",
        "id": "67",
        "photo": shrom,
        "spillyway_h": 75,
      },
      {
        "north": "18.04985",
        "east": "43.227133",
        "date": "هـ1405",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 2000000,
        "high": 18,
        "length": 21,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "عنم",
        "governorate": "سراة عبيده",
        "id": "68",
        "photo": ananm,
        "spillyway_h": 120,
      },
      {
        "north": "17.677728",
        "east": "43.346587",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 211400,
        "high": 16,
        "length": 19,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "الغائل",
        "governorate": "ظهران الجنوب",
        "id": "69",
        "photo": gaeel,
        "spillyway_h": 68,
      },
      {
        "north": "17.786944",
        "east": "43.379167",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 71900,
        "high": 10,
        "length": 13,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "الدافعه",
        "governorate": "ظهران الجنوب",
        "id": "70",
        "photo": dafaa,
        "spillyway_h": 43,
      },
      {
        "north": "17.999178",
        "east": "43.428686",
        "date": "هـ1405",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 2500000,
        "high": 20,
        "length": 23,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "الفيض",
        "governorate": "ظهران الجنوب",
        "id": "71",
        "photo": feed,
        "spillyway_h": 130,
      },
      {
        "north": "17.994082",
        "east": "43.114552",
        "date": "هـ1434",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 780000,
        "high": 13,
        "length": 17,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "قرضان",
        "governorate": "سراة عبيده",
        "id": "72",
        "photo": frdan,
        "spillyway_h": 195,
      },
      {
        "north": "18.050278",
        "east": "43.129253",
        "date": "هـ1403",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 55000,
        "high": 3,
        "length": 5,
        "type": "ترابي",
        "purpose": "حماية",
        "d_name": "السروى",
        "governorate": "سراة عبيده",
        "id": "73",
        "photo": saroi,
        "spillyway_h": 120,
      },
      {
        "north": "18.034772",
        "east": "43.0665",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 60000,
        "high": 8,
        "length": 10.5,
        "type": "ركامي",
        "purpose": "حماية",
        "d_name": "العسران",
        "governorate": "سراة عبيده",
        "id": "74",
        "photo": osran,
        "spillyway_h": 200,
      },
      {
        "north": "18.20185",
        "east": "42.85783",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 100000,
        "high": 2.1,
        "length": 5,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "ابوخضاعه",
        "governorate": "احد رفيده",
        "id": "75",
        "photo": abugadaa,
        "spillyway_h": 65,
      },
      {
        "north": "17.5875",
        "east": "43.541667",
        "date": "1431",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 519500,
        "high": 13,
        "length": 16,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "كتام",
        "governorate": "ظهران الجنوب",
        "id": "76",
        "photo": ktam,
        "spillyway_h": 166,
      },
      {
        "north": "17.967733",
        "east": "43.196678",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 150000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "العيزاء",
        "governorate": "سراة عبيده",
        "id": "77",
        "photo": alaiza,
        "spillyway_h": 80,
      },
      {
        "north": "17.722339",
        "east": "43.495892",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 107000,
        "high": 14,
        "length": 17,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "ال فروان",
        "governorate": "ظهران الجنوب",
        "id": "78",
        "photo": froon,
        "spillyway_h": 140,
      },
      {
        "north": "18.101472",
        "east": "43.20805",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 250000,
        "high": 7,
        "length": 10,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "وادي داف",
        "governorate": "سراة عبيده",
        "id": "79",
        "photo": wadidaf,
        "spillyway_h": 70,
      },
      {
        "north": "17.914444",
        "east": "43.248889",
        "date": "هـ1419",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 500000,
        "high": 11,
        "length": 14,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "الجوه",
        "governorate": "سراة عبيده",
        "id": "80",
        "photo": algoha,
        "spillyway_h": 122,
      },
      {
        "north": "18.134675",
        "east": "43.105861",
        "date": "هـ1400",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 1500000,
        "high": 18,
        "length": 22,
        "type": "ركامي",
        "purpose": "حماية",
        "d_name": "المحزمه",
        "governorate": "سراة عبيده",
        "id": "81",
        "photo": mohzam,
        "spillyway_h": 280,
      },
      {
        "north": "17.656353",
        "east": "43.462664",
        "date": "هـ1405",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 963000,
        "high": 22,
        "length": 28,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "عراعر",
        "governorate": "ظهران الجنوب",
        "id": "82",
        "photo": araer,
        "spillyway_h": 145,
      },
      {
        "north": "18.024167",
        "east": "43.238889",
        "date": "هـ1441",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 59232,
        "high": 11,
        "length": 14,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "الفرحة",
        "governorate": "سراة عبيده",
        "id": "83",
        "photo": farha,
        "spillyway_h": 57,
      },
      {
        "north": "17.973105",
        "east": "43.393198",
        "date": "هـ1437",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 280000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "شعب الحرجه",
        "governorate": "الحرجة",
        "id": "84",
        "photo": shabhrja,
        "spillyway_h": 62,
      },
      {
        "north": "19.799444",
        "east": "41.8825",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 252000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "خثعم",
        "governorate": "بللقرن",
        "id": "85",
        "photo": kashm,
        "spillyway_h": 50,
      },
      {
        "north": "18.5825",
        "east": "42.15",
        "date": "1431",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 325000,
        "high": 13,
        "length": 16,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "مرة",
        "governorate": "محايل",
        "id": "86",
        "photo": mara,
        "spillyway_h": 253,
      },
      {
        "north": "19.145",
        "east": "42.034006",
        "date": "1424",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 117000,
        "high": 12,
        "length": 15,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "بني قيس",
        "governorate": "المجاردة",
        "id": "87",
        "photo": bnugis,
        "spillyway_h": 120,
      },
      {
        "north": "19.579444",
        "east": "41.889444",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 200000,
        "high": 10,
        "length": 13,
        "type": "ترابي",
        "purpose": "حماية",
        "d_name": "باشوت",
        "governorate": "بللقرن",
        "id": "88",
        "photo": shot,
        "spillyway_h": 250,
      },
      {
        "north": "18.766944",
        "east": "42.260556",
        "date": "1431",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 138000,
        "high": 17,
        "length": 20,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "الخلصة",
        "governorate": "بللسمر",
        "id": "89",
        "photo": klsa,
        "spillyway_h": 94,
      },
      {
        "north": "18.982222",
        "east": "41.911111",
        "date": "هـ1431",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 275247,
        "high": 9,
        "length": 12,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "شري",
        "governorate": "بارق",
        "id": "90",
        "photo": shri,
        "spillyway_h": 208,
      },
      {
        "north": "19.549444",
        "east": "41.983333",
        "date": "هـ1401",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 300000,
        "high": 10,
        "length": 13,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "غضار",
        "governorate": "بللقرن",
        "id": "91",
        "photo": gdar,
        "spillyway_h": 157,
      },
      {
        "north": "18.908611",
        "east": "42.225278",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 264000,
        "high": 15,
        "length": 18,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "سدوان",
        "governorate": "بللسمر",
        "id": "92",
        "photo": sdwan,
        "spillyway_h": 115,
      },
      {
        "north": "19.140111",
        "east": "42.192611",
        "date": "1419",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 390000,
        "high": 8,
        "length": 11,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "سروم",
        "governorate": "النماص",
        "id": "93",
        "photo": sarom,
        "spillyway_h": 112,
      },
      {
        "north": "19.088889",
        "east": "42.046944",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 500000,
        "high": 15,
        "length": 18,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "جبل خاط",
        "governorate": "المجاردة",
        "id": "94",
        "photo": kas,
        "spillyway_h": 158,
      },
      {
        "north": "19.194981",
        "east": "41.922949",
        "date": "1431",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 600000,
        "high": 11,
        "length": 14,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "جريه المجارده",
        "governorate": "المجاردة",
        "id": "95",
        "photo": mgarda,
        "spillyway_h": 83,
      },
      {
        "north": "19.566389",
        "east": "41.8975",
        "date": "1431",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 74000,
        "high": 6,
        "length": 8,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "شعب شداد",
        "governorate": "بلقرن",
        "id": "96",
        "photo": shdad,
        "spillyway_h": 77,
      },
      {
        "north": "19.104528",
        "east": "42.143333",
        "date": "هـ1405",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 1000000,
        "high": 15,
        "length": 18,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "سرابه",
        "governorate": "النماص",
        "id": "97",
        "photo": sarba,
        "spillyway_h": 170,
      },
      {
        "north": "19.260278",
        "east": "42.0925",
        "date": "هـ1431",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 135000,
        "high": 19,
        "length": 22,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "الغرة",
        "governorate": "النماص",
        "id": "98",
        "photo": gra,
        "spillyway_h": 76,
      },
      {
        "north": "20.024502",
        "east": "42.185128",
        "date": "هـ1431",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 411226,
        "high": 6,
        "length": 8,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "مسكة",
        "governorate": "بيشة",
        "id": "99",
        "photo": mska,
        "spillyway_h": 225,
      },
      {
        "north": "19.246531",
        "east": "42.119876",
        "date": "هـ1434",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 972976,
        "high": 30,
        "length": 35,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "حلبا",
        "governorate": "النماص",
        "id": "100",
        "photo": hlba,
        "spillyway_h": 114,
      },
      {
        "north": "19.355278",
        "east": "42.090833",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 455300,
        "high": 14,
        "length": 17,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "طريف",
        "governorate": "النماص",
        "id": "101",
        "photo": trif,
        "spillyway_h": 90,
      },
      {
        "north": "18.907222",
        "east": "42.319444",
        "date": "هـ1431",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 446675,
        "high": 15,
        "length": 18,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "خرص",
        "governorate": "بللسمر",
        "id": "102",
        "photo": kars,
        "spillyway_h": 136,
      },
      {
        "north": "18.908833",
        "east": "42.208306",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 120000,
        "high": 12,
        "length": 15,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "الدهناء",
        "governorate": "النماص",
        "id": "103",
        "photo": zhna,
        "spillyway_h": 70,
      },
      {
        "north": "19.504167",
        "east": "42.185",
        "date": "هـ1433",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 2000000,
        "high": 14,
        "length": 17,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "القوباء",
        "governorate": "بيشة",
        "id": "104",
        "photo": gobaa,
        "spillyway_h": 166,
      },
      {
        "north": "19.04",
        "east": "42.215278",
        "date": "1430",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 217730,
        "high": 13,
        "length": 16,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "غالبة",
        "governorate": "تنومه",
        "id": "105",
        "photo": galb,
        "spillyway_h": 185,
      },
      {
        "north": "18.13764",
        "east": "41.641",
        "date": "هـ1417",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 2290000,
        "high": 10,
        "length": 15,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "ذهبان",
        "governorate": "البرك",
        "id": "106",
        "photo": zhban,
        "spillyway_h": 262,
      },
      {
        "north": "19.332222",
        "east": "42.835278",
        "date": "هـ1434",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 4650000,
        "high": 16,
        "length": 21,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "هرجاب",
        "governorate": "بيشه",
        "id": "107",
        "photo": hrgab,
        "spillyway_h": 203,
      },
      {
        "north": "19.522217",
        "east": "41.981979",
        "date": "هـ1402",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 325000,
        "high": 12,
        "length": 15,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "ثما",
        "governorate": "بللقرن",
        "id": "108",
        "photo": thama,
        "spillyway_h": 145,
      },
      {
        "north": "19.319167",
        "east": "42.121389",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 593000,
        "high": 20,
        "length": 23,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "عوص",
        "governorate": "النماص",
        "id": "109",
        "photo": oas,
        "spillyway_h": 127,
      },
      {
        "north": "19.740833",
        "east": "41.925694",
        "date": "1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 690000,
        "high": 8,
        "length": 11,
        "type": "ترابي",
        "purpose": "حماية",
        "d_name": "يفيف",
        "governorate": "بللقرن",
        "id": "110",
        "photo": bagif,
        "spillyway_h": 150,
      },
      {
        "north": "19.713889",
        "east": "41.897056",
        "date": "هـ1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 750000,
        "high": 11,
        "length": 14,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "نبه",
        "governorate": "بللقرن",
        "id": "111",
        "photo": naba,
        "spillyway_h": 140,
      },
      {
        "north": "19.412083",
        "east": "42.055667",
        "date": "هـ1425",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 1000000,
        "high": 14,
        "length": 17,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "عياش",
        "governorate": "النماص",
        "id": "112",
        "photo": aiash,
        "spillyway_h": 130,
      },
      {
        "north": "18.790556",
        "east": "42.305556",
        "date": "هـ1425",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 1500000,
        "high": 21,
        "length": 25,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "الغرابه",
        "governorate": "بللسمر",
        "id": "113",
        "photo": graba,
        "spillyway_h": 120,
      },
      {
        "north": "19.168061",
        "east": "42.164667",
        "date": "1428",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 2000000,
        "high": 24,
        "length": 28,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "بدوه",
        "governorate": "النماص",
        "id": "114",
        "photo": badora,
        "spillyway_h": 111,
      },
      {
        "north": "19.748056",
        "east": "41.983333",
        "date": "هـ1431",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 3000000,
        "high": 20,
        "length": 24,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "الفوهة",
        "governorate": "بلقرن",
        "id": "115",
        "photo": foha,
        "spillyway_h": 100,
      },
      {
        "north": "19.104167",
        "east": "42.295",
        "date": "هـ1434",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 9713800,
        "high": 20,
        "length": 25,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "ترجس",
        "governorate": "النماص",
        "id": "116",
        "photo": trjs,
        "spillyway_h": 184,
      },
      {
        "north": "19.953934",
        "east": "42.143974",
        "date": "هـ1436",
        "Sirens": 0,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 68410000,
        "high": 34.25,
        "length": 40.25,
        "type": "ركامي",
        "purpose": "للشرب",
        "d_name": "تبالة",
        "governorate": "بيشة",
        "id": "117",
        "photo": tbalh,
        "spillyway_h": 420,
      },
      {
        "north": "19.588889",
        "east": "41.9275",
        "date": "هـ1432",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 1,
        "capacity": 271100,
        "high": 12,
        "length": 15,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "شيهانة",
        "governorate": "بلقرن",
        "id": "118",
        "photo": shibana,
        "spillyway_h": 79,
      },
      {
        "north": "19.6964",
        "east": "42.487117",
        "date": "هـ1418",
        "Sirens": 0,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 325000000,
        "high": 60.5,
        "length": 68,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "الملك فهد",
        "governorate": "بيشة",
        "id": "119",
        "photo": king,
        "spillyway_h": 507,
      },
      {
        "north": "19.014722",
        "east": "41.643889",
        "date": "",
        "Sirens": 0,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 80913300,
        "high": 40,
        "length": 47,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "يبة",
        "governorate": "بارق",
        "id": "120",
        "photo": ubh,
        "spillyway_h": 234,
      },
      {
        "north": "19.196389",
        "east": "42.1375",
        "date": "",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 211779,
        "high": 22.5,
        "length": 26,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "حضر",
        "governorate": "النماص",
        "id": "121",
        "photo": kder,
        "spillyway_h": 111,
      },
      
  ];
  
  export default Sade;
  