import Wesanb from '../iamge/wesanb.png';
import Radwan from '../iamge/radwan.png';
import Madaa from '../iamge/madaa.png';
import Msireg from '../iamge/msireg.png';
import Oad from '../iamge/oad.png';
import Rada from '../iamge/rada.png';
import Reeima from '../iamge/reeima.png';
import Hswa from '../iamge/hswa.png';
import Bhwan from '../iamge/bhwan.png';
import Reem from '../iamge/reem.png';
import Sharf from '../iamge/sharf.png';
import Roam from '../iamge/roam.png';
import Soda from '../iamge/soda.png';
import Tib from '../iamge/tib.png';
import Btna from '../iamge/btna.png';
import Thoaba from '../iamge/thoaba.png'
import Khdar from '../iamge/khdar.png'
import marba from '../iamge/marba.png'
import ashran from '../iamge/ashran.png'
import tndha from '../iamge/tndha.png'
import anod from '../iamge/anod.png'
import thll from '../iamge/thll.png'

const Sade = [
   
    {
      "north": "18.280217",
      "east": "42.33365",
      "date": "1406",
      "Sirens": 1,
      "Portals": 1,
      "valves": 0,
      "Lighting": 0,
      "Generator": 1,
      "Guard": 1,
      "management": 1,
      "i_security": 1,
      "capacity": 35000,
      "high": 9,
      "length": 12,
      "type": "خرساني",
      "purpose": "حماية",
      "d_name": "العوص",
      "governorate": "رجال المع",
      "id": "1",
      "photo":Oad,
      "spillyway_h": 55,
    },

    {
      "north":"18.235867",
      "east":"42.178497",
      "date": "1403هـ",
      "Sirens": 1,
      "Portals": 0,
      "valves": 0,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 50000,
      "high": 8,
      "length": 11,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "ريم",
      "governorate": "رجال المع",
      "id": "2",
      "photo":Reem,
      "spillyway_h": 55,
    },

    {
      "north": "18.29138",
      "east": "42.444115",
      "date": "1404هـ",
      "Sirens": 1,
      "Portals": 0,
      "valves": 0,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 60000,
      "high": 12,
      "length": 15,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "ال عاصم",
      "governorate": "أبها",
      "id": "3",
      "photo": "",
      "spillyway_h": 70,
    },
    {
      "north": "18.236389",
      "east": "42.412778",
      "date": "1404هـ",
      "Sirens": 1,
      "Portals": 0,
      "valves": 0,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 340000,
      "high": 10,
      "length": 13,
      "type": "خرساني",
      "purpose": "حماية",
      "d_name": "السوده(المقضى)",
      "governorate": "أبها",
      "id": "4",
      "photo": "",
      "spillyway_h": 28,
    },
    {
      "north": "18.266239",
      "east": "42.270122",
      "date": "1404",
      "Sirens": 1,
      "Portals": 0,
      "valves": 1,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 230000,
      "high": 8,
      "length": 11,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "ثعابه",
      "governorate": "رجال المع",
      "id": "6",
      "photo":Thoaba,
      "spillyway_h": 100,
    },
    {
      "north": "18.858056",
      "east": "42.655278",
      "date": "1404",
      "Sirens": 1,
      "Portals": 0,
      "valves": 0,
      "Lighting": 0,
      "Generator": 0,
      "Guard": 0,
      "management": 0,
      "i_security": 0,
      "capacity": 151800,
      "high": 10,
      "length": 13,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "البطنه",
      "governorate": "خميس مشيط",
      "id": "7",
      "photo":Btna,
      "spillyway_h": 360,
    },
    {
      "north": "18.329722",
      "east": "42.0925",
      "date": "1406",
      "Sirens": 1,
      "Portals": 1,
      "valves": 1,
      "Lighting": 1,
      "Generator": 1,
      "Guard": 1,
      "management": 1,
      "i_security": 1,
      "capacity": 1500000,
      "high": 13,
      "length": 16,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "روام",
      "governorate": "رجال المع",
      "id": "8",
      "photo":Roam,
      "spillyway_h": 57,
    },
    {
      "north": "18.355",
      "east": "42.386389",
      "date": "1431هـ",
      "Sirens": 1,
      "Portals": 1,
      "valves": 1,
      "Lighting": 1,
      "Generator": 1,
      "Guard": 1,
      "management": 1,
      "i_security": 1,
      "capacity": 230000,
      "high": 12,
      "length": 15,
      "type": "خرساني",
      "purpose": "استعاضة",
      "d_name": "ريمه",
      "governorate": "أبها",
      "id": "9",
      "photo":Reeima,
      "spillyway_h": 205,
    },
    {
      "north": "18.447222",
      "east": "43.371389",
      "date": "1432هـ",
      "Sirens": 1,
      "Portals": 1,
      "valves": 1,
      "Lighting": 1,
      "Generator": 0,
      "Guard": 0,
      "management": 1,
      "i_security": 1,
      "capacity": 355650,
      "high": 6,
      "length": 8,
      "type": "ترابي",
      "purpose": "استعاضة",
      "d_name": "طليحة الشرف",
      "governorate": "ابها",
      "id": "10",
      "photo":Sharf,
      "spillyway_h": 281,
    },
      {
        "north": "18.358056",
        "east": "42.240833",
        "date": "1406",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 182000,
        "high": 20,
        "length": 23,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "وسانب",
        "governorate": "رجال المع",
        "id": "12",
        "photo": Wesanb,
        "spillyway_h": 100,
      },
      {
        "north": "18.236714",
        "east": "42.205464",
        "date": "1406",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 192000,
        "high": 15,
        "length": 18,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "راده",
        "governorate": "رجال المع",
        "id": "13",
        "photo": Rada,
        "spillyway_h": 70,
      },
      {
        "north": "18.053333",
        "east": "42.2683",
        "date": "1403هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 300000,
        "high": 5.5,
        "length": 8,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "العاينه",
        "governorate": "رجال المع",
        "id": "14",
        "photo": "",
        "spillyway_h": 80,
      },
      {
        "north": "18.578056",
        "east": "42.818056",
        "date": "1437",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 357160,
        "high": 4,
        "length": 6.5,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "روضان",
        "governorate": "خميس مشيط",
        "id": "15",
        "photo": "",
        "spillyway_h": 169,
      },
      {
        "north": "18.263611",
        "east": "43.601389",
        "date": "1417هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 500000,
        "high": 15,
        "length": 18,
        "type": "خرساني",
        "purpose": "جوفي",
        "d_name": "وسط مرمى",
        "governorate": "خميس مشيط",
        "id": "16",
        "photo": "",
        "spillyway_h": 85,
      },
      {
        "north": "18.295806",
        "east": "42.654453",
        "date": "1398هـ",
        "Sirens": 0,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 1000000,
        "high": 8,
        "length": 12,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "حجلا",
        "governorate": "أبها",
        "id": "17",
        "photo": "",
        "spillyway_h": 180,
      },
      {
        "north": "18.6825",
        "east": "42.413611",
        "date": "1432هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 121560,
        "high": 8,
        "length": 11,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "بهوان",
        "governorate": "أبها",
        "id": "18",
        "photo": Bhwan,
        "spillyway_h": 275,
      },
      {
        "north": "18.367438",
        "east": "42.361866",
        "date": "1403هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 90000,
        "high": 10,
        "length": 13,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "طبب",
        "governorate": "أبها",
        "id": "19",
        "photo": Tib,
        "spillyway_h": 50,
      },
      {
        "north": "19.049444",
        "east": "42.908611",
        "date": "1430هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 433000,
        "high": 6,
        "length": 9,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "المسيرق",
        "governorate": "خميس مشيط",
        "id": "20",
        "photo": "",
        "spillyway_h": 84,
      },
      {
        "north": "18.787722",
        "east": "43.210619",
        "date": "1404هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 4250000,
        "high": 6.5,
        "length": 8,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "المضه",
        "governorate": "خميس مشيط",
        "id": "21",
        "photo": "",
        "spillyway_h": 1070,
      },
      {
        "north": "43.210619",
        "east": "18.787722",
        "date": "1404هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 4250000,
        "high": 6.5,
        "length": 8,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "المضه",
        "governorate": "خميس مشيط",
        "id": "22",
        "photo": "",
        "spillyway_h": 1070,
      },
      {
        "north": "18.204321",
        "east": "42.31512",
        "date": "1404",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 200000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "حسوه",
        "governorate": "رجال المع",
        "id": "23",
        "photo": "",
        "spillyway_h": 45,
      },
      {
        "north": "18.677844",
        "east": "42.331407",
        "date": "1432هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 229700,
        "high": 10,
        "length": 13,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "صبح",
        "governorate": "أبها",
        "id": "24",
        "photo": "",
        "spillyway_h": 130,
      },
      {
        "north": "18.023",
        "east": "42.7637",
        "date": "1405",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 300000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "تمنية",
        "governorate": "أبها",
        "id": "25",
        "photo": "",
        "spillyway_h": 100,
      },
      {
        "north": "18.650156",
        "east": "42.397278",
        "date": "1404هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 400000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "الماوين",
        "governorate": "أبها",
        "id": "26",
        "photo": "",
        "spillyway_h": 120,
      },
      {
        "north": "18.269167",
        "east": "42.438056",
        "date": "1404",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 1500000,
        "high": 31.5,
        "length": 38,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "عشران",
        "governorate": "أبها",
        "id": "27",
        "photo": "",
        "spillyway_h": 111,
      },
      {
        "north": "18.850858",
        "east": "42.855842",
        "date": "1405هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 0,
        "Generator": 1,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 1064000,
        "high": 8,
        "length": 11,
        "type": "خرساني",
        "purpose": "استعاضة",
        "d_name": "اثب",
        "governorate": "خميس مشيط",
        "id": "28",
        "photo": "",
        "spillyway_h": 95,
      },
      {
        "north": "18.695833",
        "east": "42.527222",
        "date": "1431هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 1128733,
        "high": 6,
        "length": 9,
        "type": "ترابي",
        "purpose": "حماية",
        "d_name": "خضار الحيمة",
        "governorate": "خميس مشيط",
        "id": "29",
        "photo": "",
        "spillyway_h": 648,
      },
      {
        "north": "18.403611",
        "east": "42.4",
        "date": "1405",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 0,
        "Generator": 1,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 140000,
        "high": 10.5,
        "length": 13.5,
        "type": "ركامي",
        "purpose": "استعاضة",
        "d_name": "تهلل",
        "governorate": "أبها",
        "id": "30",
        "photo": "",
        "spillyway_h": 140,
      },
      {
        "north": "18.209935",
        "east": "42.488654",
        "date": "1394هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 0,
        "i_security": 1,
        "capacity": 2130000,
        "high": 22.5,
        "length": 25.5,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "أبها",
        "governorate": "أبها",
        "id": "31",
        "photo": "",
        "spillyway_h": 350,
      },
      {
        "north": "18.312683",
        "east": "42.876847",
        "date": "1404هـ",
        "Sirens": 1,
        "Portals": 1,
        "valves": 1,
        "Lighting": 1,
        "Generator": 0,
        "Guard": 1,
        "management": 1,
        "i_security": 0,
        "capacity": 4200000,
        "high": 10,
        "length": 16,
        "type": "خرساني",
        "purpose": "للشرب",
        "d_name": "تندحه",
        "governorate": "خميس مشيط",
        "id": "32",
        "photo": "",
        "spillyway_h": 120,
      },
      {
        "north": "18.260411",
        "east": "42.715894",
        "date": "1402هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 0,
        "i_security": 1,
        "capacity": 6240000,
        "high": 16,
        "length": 22,
        "type": "ركامي",
        "purpose": "للشرب",
        "d_name": "عتود",
        "governorate": "خميس مشيط",
        "id": "33",
        "photo": "",
        "spillyway_h": 340,
      },
      {
        "north": "17.850739",
        "east": "42.386114",
        "date": "1428هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 0,
        "Generator": 1,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 7000000,
        "high": 0,
        "length": 28,
        "type": "جوفي",
        "purpose": "للشرب",
        "d_name": "عتود الجوفي",
        "governorate": "أبها",
        "id": "34",
        "photo": "",
        "spillyway_h": 456,
      },
      {
        "north": "17.903333",
        "east": "42.384722",
        "date": "1429",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 10000000,
        "high": 26,
        "length": 32,
        "type": "ترابي",
        "purpose": "للشرب",
        "d_name": "مربة",
        "governorate": "مربة",
        "id": "35",
        "photo": "",
        "spillyway_h": 215,
      },
      {
        "north": "17.900556",
        "east": "42.471111",
        "date": "1429",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 1,
        "Generator": 1,
        "Guard": 1,
        "management": 1,
        "i_security": 1,
        "capacity": 10000000,
        "high": 29,
        "length": 35,
        "type": "ترابي",
        "purpose": "للشرب",
        "d_name": "عتود",
        "governorate": "أبها",
        "id": "36",
        "photo": "",
        "spillyway_h": 227,
      },
      {
        "north": "18.280428",
        "east": "42.864847",
        "date": "1406هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 1,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 0,
        "i_security": 0,
        "capacity": 3000000,
        "high": 7,
        "length": 10,
        "type": "ترابي",
        "purpose": "استعاضة",
        "d_name": "عقده",
        "governorate": "خميس مشيط",
        "id": "37",
        "photo": "",
        "spillyway_h": 220,
      },
      {
        "north": "19.245278",
        "east": "43.138611",
        "date": "1440هـ",
        "Sirens": 1,
        "Portals": 0,
        "valves": 0,
        "Lighting": 0,
        "Generator": 0,
        "Guard": 0,
        "management": 1,
        "i_security": 0,
        "capacity": 639068,
        "high": 5.5,
        "length": 8.5,
        "type": "خرساني",
        "purpose": "حماية",
        "d_name": "الثفن",
        "governorate": "خميس مشيط",
        "id": "38",
        "photo": "",
        "spillyway_h": 189,
      },
  ];
  
  export default Sade;
  